### ISSUE TITLE
Error in Fining People.

### ISSUE THREAD

**Issue by Vandam** [FXServer-ESX/fxserver-esx_policejob#5]
I have Several Issues,

Issue 1:  When trying to fine someone, it gives me this error in server console:

`Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: citizen
:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:338: in local 'cb'
        server/main.lua:85: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>
Error running call reference function for resource esx_billing: server/main.lua:16: attempt to index a number value (local 'v')
stack traceback:
        server/main.lua:16: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:277: in function <citizen:/scripting/lua/scheduler.lua:268>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:33: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>
Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: citizen
:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:338: in local 'cb'
        server/main.lua:85: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>`

Error 2: When joining the Police, the player model is not changed to a Police ID. Can this be fixed?

**Comment by indilo53** [comment]
Issue 1 : Update esx_billng
Issue 2 : There is a cloakroom to change your outfit
